update user details
Rishab-innovative/firebase pull request #4
Opened 2023-11-18 13:59 UTC by Rishab-innovative

2023-11-21 12:37 UTC, PiyushInnotech commented on src/pages/EditDetailsPage.tsx
> +  useEffect(() => {
remove these

2023-11-21 12:39 UTC, PiyushInnotech commented on src/pages/EditDetailsPage.tsx
> +  const handleSuccessSignUp = () => {
change name

2023-11-21 12:43 UTC, PiyushInnotech commented on src/redux/EditDetailsSlice.tsx
> +export const SaveEditedProfilePicture = createAsyncThunk(
use same function fpr both

2023-11-21 12:48 UTC, PiyushInnotech commented on src/pages/EditDetailsPage.tsx
> +        <Modal open={openCloseModal} onClose={() => setOpenCloseModal(false)}>
create separate component for successmodal with dynamic

2023-11-29 07:19 UTC, meanstack9716 requested changes

2023-11-29 07:19 UTC, meanstack9716 commented on src/App.tsx
> +import EditDetailsPage from "./pages/EditDetailsPage";
EditUserDetil page @Rishab-innovative

2023-11-29 07:19 UTC, meanstack9716 commented on src/App.tsx
> +import { useSelector } from "react-redux";
always import all library on the top, the all our components and services @Rishab-innovative

2023-11-29 07:19 UTC, meanstack9716 commented on src/App.tsx
> +import { useSelector } from "react-redux";
this is for all pages @Rishab-innovative

2023-11-29 07:19 UTC, meanstack9716 commented on src/App.tsx
> +  const SuccessSignUp = useSelector(
variable name should start with lowerCase @Rishab-innovative

2023-11-29 07:38 UTC, merged